name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job pour exécuter les tests unitaires
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Installe les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Exécute les tests unitaires
      - name: Run Unit Tests
        run: python test.py

  # Job pour déployer l'application sur une machine auto-hébergée
  deploy:
    needs: unit_tests
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build l'image Docker localement (sans DockerHub)
      - name: Build Docker image
        run: |
          docker build -t your-app:${{ github.sha }} .

      # Déploie l'application via Docker Compose
      - name: Deploy app
        run: |
          export APP_VERSION=${{ github.sha }}
          docker-compose -f docker-compose.yml up -d
